example-0:
	gcc `pkg-config --cflags gtk+-3.0` -o example-0.out Example-0.C `pkg-config --libs gtk+-3.0`

example-1:
	gcc `pkg-config --cflags gtk+-3.0` -o example-1.out Example-1.C `pkg-config --libs gtk+-3.0`
