example-0:
	g++ Example-0.cpp -o example-0.out `pkg-config gtkmm-3.0 --cflags --libs`

example-1:
	g++ Example-1/HelloWorld.cpp Example-1/Main.cpp -o example-1.out `pkg-config gtkmm-3.0 --cflags --libs`
