synchro:
	g++ -lboost_system -lboost_thread synchroServer/Server.cpp -o synchroServer/synchro.out

async:
	g++ -lboost_system -lboost_thread asyncServer/Main.cpp asyncServer/TcpConnection.cpp asyncServer/TcpServer.cpp -o asyncServer/async.out

reader:
	g++ -lboost_system -lboost_thread asioReader/Server.cpp -o asioReader/reader.out
