synchro:
	g++ -lboost_system -lboost_thread synchroServer/Server.C -o synchroServer/synchro.out

async:
	g++ -lboost_system -lboost_thread asyncServer/Main.C asyncServer/TcpConnection.C asyncServer/TcpServer.C -o asyncServer/async.out

reader:
	g++ -lboost_system -lboost_thread asioReader/Server.C -o asioReader/reader.out
